export enum PermissionModule {
  DASHBOARD = "DASHBOARD",

  COMPANY = "COMPANY",
  ORGANIZATION = "ORGANIZATION",
  BRANCH = "BRANCH",

  ROLE = "ROLE",
  USER = "USER",
  PERMISSION = "PERMISSION",

  DEPARTMENT = "DEPARTMENT",
  DESIGNATION = "DESIGNATION",
  EMPLOYEE = "EMPLOYEE",

  CLIENT = "CLIENT",
  VENDOR = "VENDOR",

  PROJECT = "PROJECT",
  PROJECT_CATEGORY = "PROJECT_CATEGORY",
  PROJECT_ROLE = "PROJECT_ROLE",

  TASK = "TASK",

  INVENTORY = "INVENTORY",
  PURCHASE = "PURCHASE",

  FINANCE = "FINANCE",

  REPORT = "REPORT",

  SETTINGS = "SETTINGS",

  // Platform modules
  PLATFORM_COMPANY = "PLATFORM_COMPANY",
  PLATFORM_ROLE = "PLATFORM_ROLE",
  PLATFORM_USER = "PLATFORM_USER",
  PLATFORM_PERMISSION = "PLATFORM_PERMISSION",
  PLATFORM_MODULE = "PLATFORM_MODULE",
  PLATFORM_SUBSCRIPTION_PLAN = "PLATFORM_SUBSCRIPTION_PLAN",
  PLATFORM_VENDOR = "PLATFORM_VENDOR",
  PLATFORM_VENDOR_CATEGORY = "PLATFORM_VENDOR_CATEGORY",
}