export enum PermissionModule {
  DASHBOARD = "DASHBOARD",

  COMPANY = "COMPANY",
  ORGANIZATION = "ORGANIZATION",
  BRANCH = "BRANCH",

  ROLE = "ROLE",
  USER = "USER",

  HR = "HR",
  DEPARTMENT = "DEPARTMENT",
  DESIGNATION = "DESIGNATION",
  EMPLOYEE = "EMPLOYEE",

  CLIENT = "CLIENT",
  VENDOR = "VENDOR",

  PROJECT = "PROJECT",

  INVENTORY = "INVENTORY",
  PURCHASE = "PURCHASE",

  FINANCE = "FINANCE",

  REPORT = "REPORT",

  SETTINGS = "SETTINGS",
}