services:
  postgres:
    image: postgres:16-alpine

    container_name: matrix-crm-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: matrix_crm

    ports:
      - "55432:5432"

    volumes:
      - crm_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d matrix_crm"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - matrix-crm-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev

    container_name: matrix-crm-backend

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - ../backend/.env

    environment:
      NODE_ENV: development
      PORT: 3000

      # Docker container ke andar localhost use nahi hoga.
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/matrix_crm?schema=public

      FRONTEND_URL: http://localhost:5173

    ports:
      - "3000:3000"

    volumes:
      - ../backend:/app
      - crm_backend_node_modules:/app/node_modules

    command:
      - npm
      - run
      - start:dev

    networks:
      - matrix-crm-network

  admin:
    build:
      context: ../admin
      dockerfile: Dockerfile.dev

    container_name: matrix-crm-admin

    restart: unless-stopped

    depends_on:
      - backend

    env_file:
      - ../admin/.env.development

    environment:
      VITE_API_BASE_URL: http://localhost:3000/api/v1

    ports:
      - "5173:5173"

    volumes:
      - ../admin:/app
      - crm_admin_node_modules:/app/node_modules

    command:
      - npm
      - run
      - dev
      - --
      - --host
      - 0.0.0.0

    networks:
      - matrix-crm-network

volumes:
  crm_postgres_data:
  crm_backend_node_modules:
  crm_admin_node_modules:

networks:
  matrix-crm-network:
    driver: bridge
